# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Set up env
      run: echo "BUILD_VERSION=`git rev-list --count origin/master`" >> $GITHUB_ENV
    - name: Initialize submodules
      run: git submodule update --remote
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar -Dorg.gradle.daemon=false -PbuildVersion="${{ env.BUILD_VERSION }}"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: build/libs/${{ github.event.repository.name }}.jar
